apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ecommerce-devops
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: http
    port: 80
    targetPort: 3001
    protocol: TCP