name: CI - Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'kube/**'
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
  IMAGE_TAG: latest 
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Checkout Repository
      uses: actions/checkout@v4

    - name: 2. Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 3. Build and Push Backend Image
      run: |
  
        DOCKER_IMAGE="${{ env.DOCKER_USERNAME }}/ecommerce-backend:${{ env.IMAGE_TAG }}"
      
        docker build ./ecommerce-app-backend/ -t $DOCKER_IMAGE
        docker push $DOCKER_IMAGE

    - name: 4. Build and Push Frontend Image
      run: |
        # اسم الصورة: [اسم المستخدم]/frontend:latest
        DOCKER_IMAGE="${{ env.DOCKER_USERNAME }}/ecommerce-frontend:${{ env.IMAGE_TAG }}"
        
        docker build ./ecommerce-app-frontend/ \
          -t $DOCKER_IMAGE
        
        docker push $DOCKER_IMAGE
