name: CI - Build & Push Docker Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
  ACR_NAME: ${{ secrets.AZURE_ACR_NAME }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
    - name: 1. Checkout Repository
      uses: actions/checkout@v4


    - name: 2. Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

  
    - name: 3. Build and Push Backend Image
      run: |
        docker build ./ecommerce-app-backend -t ${{ env.DOCKER_USERNAME }}/ecommerce-backend:latest
        docker push ${{ env.DOCKER_USERNAME }}/ecommerce-backend:latest

    - name: 4. Build and Push Frontend Image
      run: |
        docker build ./ecommerce-app-frontend -t ${{ env.DOCKER_USERNAME }}/ecommerce-frontend:latest
        docker push ${{ env.DOCKER_USERNAME }}/ecommerce-frontend:latest
        
 
    - name: 5. Azure Login for ACR
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}


    - name: 6. Push Images to Azure ACR
      run: |
        # Tagging for ACR and pushing
        docker tag ${{ env.DOCKER_USERNAME }}/ecommerce-backend:latest ${{ env.ACR_NAME }}.azurecr.io/ecommerce-backend:latest
        docker tag ${{ env.DOCKER_USERNAME }}/ecommerce-frontend:latest ${{ env.ACR_NAME }}.azurecr.io/ecommerce-frontend:latest
        
        # Pushing to ACR
        az acr login --name ${{ env.ACR_NAME }}
        docker push ${{ env.ACR_NAME }}.azurecr.io/ecommerce-backend:latest
        docker push ${{ env.ACR_NAME }}.azurecr.io/ecommerce-frontend:latest
