name: CI - Build and Push Docker Images (Docker Hub)

on:
push:
branches:
- main
workflow_dispatch: 
env:
DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}
IMAGE_TAG: latest

jobs:
build_and_push:
runs-on: ubuntu-latest

steps:
- name: 1. Checkout Repository
  uses: actions/checkout@v4

- name: 2. Login to Docker Hub
  uses: docker/login-action@v3
  with:
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}

# --- Backend Service ---
- name: 3. Build and Push Backend Image
  run: |
    docker build -t ${{ env.DOCKER_IMAGE }}/ecommerce-backend:${{ env.IMAGE_TAG }} ./ecommerce-app-backend
    docker push ${{ env.DOCKER_IMAGE }}/ecommerce-backend:${{ env.IMAGE_TAG }}

# --- Frontend Service ---
- name: 4. Build and Push Frontend Image
  run: |
    docker build -t ${{ env.DOCKER_IMAGE }}/ecommerce-frontend:${{ env.IMAGE_TAG }} ./ecommerce-app-frontend
    docker push ${{ env.DOCKER_IMAGE }}/ecommerce-frontend:${{ env.IMAGE_TAG }}
